### ISSUE TITLE
Some errors come as excuting the following commands.

### ISSUE THREAD

**Issue by xiaopaoge** [geocompass/robosat_buildings_training#1]
docker run  -v $PWD:/data --ipc=host --network=host mapbox/robosat:latest-cpu download http://ditu.google.cn/maps/vt/lyrs=s&x={x}&y={y}&z={z} /data/buildings.tiles /data/tiles
[3] 27464
[4] 27465
[5] 27466
-bash: /data/buildings.tiles: No such file or directory
But it really exist in $PWD directory.      Should I do something to resolve  it.

**Comment by wucangeo** [comment]
Hi.
Robosat do not support WMTS url like `x={x}&y={y}&z={z} `, you could try `/{z}/{x}/{y}` format.
I made a tool to solve this, it's [xyz_proxy](https://github.com/geocompass/robosat_geoc/blob/master/xyz_proxy.py).

If you want to use `docker` command in robosat, you should find the *Tutorial* in [https://github.com/mapbox/robosat](https://github.com/mapbox/robosat).
`robosat_buildings_training` focus on using Flask to call robosat command tools, to make it flexible, in production mode. 

And, this repository No Longer Maintained.
You may interest in [https://github.com/geocompass/robosat_geoc](https://github.com/geocompass/robosat_geoc), better, more powerfull.

**Comment by xiaopaoge** [comment]
Hi.
Thanks for your help.I will try it &nbsp;later.
Best wishes!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wucan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 凌晨0:10
收件人:&nbsp;"geocompass/robosat_buildings_training"<robosat_buildings_training@noreply.github.com&gt;;
抄送:&nbsp;"孤星泪"<1060313038@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [geocompass/robosat_buildings_training] Some errors come as excuting the following commands. (#1)




Hi.
 Robosat do not support WMTS url like x={x}&amp;y={y}&amp;z={z} , you could try /{z}/{x}/{y} format.
 I made a tool to solve this, it's xyz_proxy.
 
If you want to use docker command in robosat, you should find the Tutorial in https://github.com/mapbox/robosat.
 robosat_buildings_training focus on using Flask to call robosat command tools, to make it flexible, in production mode.
 
And, this repository No Longer Maintained.
 You may interest in https://github.com/geocompass/robosat_geoc, better, more powerfull.
