### ISSUE TITLE
predict会出现一堆

### ISSUE THREAD

**Issue by xttyui** [geocompass/robosat_buildings_training#4]
每次运行predict都会出现一堆奇怪的东西也不知道是啥问题3c2e8f8cb80c850ffbc7c6ea58ce9f0b194c3b097f6eae81380a6fe2424c47bf
每次都不一样

**Comment by Githubwujinming** [comment]
你好，我遇到吧相同的问题，请问你是怎么解决的呢

> 每次运行predict都会出现一堆奇怪的东西也不知道是啥问题3c2e8f8cb80c850ffbc7c6ea58ce9f0b194c3b097f6eae81380a6fe2424c47bf
> 每次都不一样

**Comment by Githubwujinming** [comment]
是因为docker -d 参数，程序后台运行了，去掉d参数就会输出信息了
